### ISSUE TITLE
Clarification of installation and/or addition to crates.io

### ISSUE THREAD

**Issue by BnDLett** [JLannoo/wiz-lights#1]
I love the idea of the code, and I am completely willing to use it -- however, it would be convenient if the code was uploaded to crates.io.

**Comment by JLannoo** [comment]
Hi there!

Thanks for expressing support for the project! It was mostly a learning experiment for Rust and its module system.

Sadly, I've placed it (along with Rust) in the back burner for a while. As you might have seen, the last commit was almost a year ago.
I've run into some roadblocks because of some of the foundations of the project. Certain future functionalities need reworking from the ground up, which is something I'm not comfortable enough in this language to do yet.

If you want to contribute to the project, you are more than welcome. But keep in mind these issues I've mentioned.

I'm currently developing a [version of this in Typescript](https://github.com/JLannoo/wiz-lights-manager) (where I feel more comfortable working), if you are interested. 
It is much more polished, better built and might work as a reference for this Rust version in the future.

Hopefully this is something I will come back to sometime. But I don't have plans to do it anytime soon, sorry.

**Comment by BnDLett** [comment]
I see, that's entirely understandable. I do intend on contributing on the project (in fact, I already have some code cooked up), but not by much. Mostly just some things that I think are more convenient. 

Either way, I do wish you the best of luck with the version in Typescript. I can't say that I'm interested given that I write primarily in Python and I am just doing Rust purely for the fun of it, but I might check it out sometime in the future.
